apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-getting-start
  labels:
    app: quarkus-getting-start
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-getting-start
  template:
    metadata:
      labels:
        app: quarkus-getting-start
    spec:
      containers:
      - image: chihkang/hello-quarkus:linux-arm64
#         image: chihkang/quarkus-quickstart:1.0.0-multistage
        name: quarkus-getting-start
        ports:
        - containerPort: 8080
